BitGo/kustomize-loki

loki/README.md
loki/files/config.yaml

https://github.com/grafana/loki/issues/3069 is partially addressed;
however an empty S3 url is still required to avoid loki reaching out to sts.dummy.amazonaws.com

loki: its now possible to use bucketnames

---

loki/files/config.yaml

Contrary to [loki documentation](https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration)
---
I noticed that we've been hitting max number of tails a lot lately; checking out the live config (e.g. `kubectl exec -it deploy/query-frontend -- wget -O- http://localhost:3100/config`) I saw that `max_concurrent_tail_requests` was `0` rather than the expected `100`. Adding a hyphen to the syntax (which is how default values work in bash) made the config value `100` as desired.
As a follow-up, this issue should be reported to loki upstream.

loki: default value syntax is ${env_var:-default} with a hyphen

---

loki/files/config.yaml

The promtail pod in charge of ingesting logs from the platform-mongo primary looks like it's being rate limited:
`
server returned HTTP status 429 Too Many Requests (429): Ingestion rate limit exceeded (limit: 3495253 bytes/sec) while attempting to ingest '696' lines totaling '1048147' bytes, reduce log volume or contact your Loki administrator to see if the limit can be increased
`
MongoDB is extremely verbose in its log output, even on the lowest setting.

loki: increase ingester limits

---

loki/files/config.yaml

Reintroduce the old default values, which are from the loki team recommended config:
https://github.com/grafana/loki/blob/e16f1fef81e199d25e5cb43b6f285750dd0cb35f/production/ksonnet/loki/config.libsonnet#L196-L197

loki: introduce env vars to override ingester limits

---

loki/files/config.yaml

Add ability to change this setting via envvar.
Default value is 60s: https://grafana.com/docs/loki/latest/configuration/#querier_config

loki: querier, add ability to adjust loki querier timeout

---

loki/files/config.yaml

See https://github.com/grafana/loki/issues/4136

loki: default remote_client client url to the empty string

---

loki/files/config.yaml

The syntax is `:-` rather than `:`.
i.e. https://github.com/BitGo/kustomize-loki/pull/4 all over again
Introduced in https://github.com/BitGo/kustomize-loki/pull/17/

loki: fix invalid env var expansion

---

loki/README.md
loki/index-gateway/apps-v1.StatefulSet-index-gateway.yaml
loki/index-gateway/kustomization.yaml
loki/index-gateway/querier-kind.patch.yaml
loki/index-gateway/server-address.patch.yaml
loki/index-gateway/v1.Service-index-gateway.yaml
loki/kustomization.yaml

As mentioned in #11 
From Loki 2.3.0 release notes:
> We created an index gateway which takes on the task of downloading the boltdb-shipper index files allowing you to run your queriers without any local disk requirements, this is really helpful in Kubernetes environments where you can return your queriers from Statefulsets back to Deployments and save a lot of PVC costs and operational headaches.
There's not many docs available right now; there's a little mentioned at https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/#index-gateway

loki: use index-gateway

---

loki/index-gateway/querier-kind.patch.yaml

Workaround until https://github.com/kubernetes-sigs/kustomize/issues/4136 is fixed.
Even after it is fixed we'll need to bump the minimum required kustomize version; so could be non-trivial.
Fixes #27

loki: disable the change of querier kind until kustomize bug is fixed

---

loki/recording-rules.yaml

Reported via @RyanSquared  at https://github.com/BitGo/kustomize-loki/commit/c9cd5c2ec4254142a4d2caa80d9a07b7a41d4866#commitcomment-55914056; thankyou!
Before:
```
$ yq .spec loki/recording-rules.yaml > tmp.yaml
$ cortextool rules check --log.level=debug tmp.yaml 
INFO[0000] log level set to debug                       
ERRO[0000] unable parse rules file                       error="79:19: group \"loki.rules\", rule 18, \"node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate\": could not parse expression: 1:44: parse error: ranges only allowed for vector selectors" file=tmp.yaml
cortextool: error: check operation unsuccessful, unable to parse rules files: file read error, try --help
```
After:
```
$ yq .spec loki/recording-rules.yaml > tmp.yaml
$ cortextool rules check …
```

loki: fix invalid recording rule

---

loki/recording-rules.yaml

The loki operational dashboard uses e.g. `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace="loki", pod=~"distributor.*"}`
This is failing as the `namespace` label is missing from our recording rule.
I assume based on the rule name, it was supposed to be across node, namespace, pod, container.

loki: node_namespace_pod_container rule should be by node+namespace

---

loki/files/config.yaml

New env var `LOKI_QUERIER_ENGINE_TIMEOUT`
This is the timeout for query execution, and probably want people want rather
than `LOKI_QUERIER_QUERY_TIMEOUT`, which is the timeout for the queriers
talking to ingesters/backing storage.

loki: allow querier engine timeout to be configured

---

promtail/files/promtail.yaml

Currently pods with *no* controller are getting their logs picked up twice.
Once by kubernetes-pods-direct-controllers (unintentionally), and also by
kubernetes-other (intentionally).
This commit fixes the kubernetes-pods-direct-controllers job

promtail: drop pods with no controller from direct-controller job

---

loki-canary/resources.yaml

loki-canary: run as non-root

---

loki-canary/kustomization.yaml
loki/apps-v1.StatefulSet-ingester.yaml
loki/files/config.yaml
loki/ingress/ingress.yaml
loki/kustomization.yaml
loki/ruler-sidecar/kustomization.yaml
promtail/kustomization.yaml
promtail/resources.yaml

Release Notes:
- https://github.com/grafana/loki/releases/tag/v2.4.0
- https://github.com/grafana/loki/releases/tag/v2.4.1
Upgrade notes: https://github.com/grafana/loki/blob/90d5d24998e44e9c0bdb0517a9d518f29b72a75b/docs/sources/upgrading/_index.md#240
- Enable ingester WAL
- Out-of-order writes is [now on by default](https://github.com/grafana/loki/blob/e52e8051447726f69d426df3f79fac3cb1384524/docs/sources/configuration/_index.md#accept-out-of-order-writes)
Replaces #26

Loki 2.4.1 release

---

loki/files/config.yaml

This removes several config values that are now being set to their default.
`frontend_worker.parallelism` is the only actual change, which *should* be set to the same as `max_concurrent` anyway.
See https://github.com/grafana/loki/pull/5077 for some more info

loki: clean up config to remove defaults

---

loki/ruler-sidecar/kustomization.yaml

https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.15.1

loki/ruler-sidecar: update k8s-sidecar to 1.15.1

---

loki/apps-v1.StatefulSet-compactor.yaml
loki/apps-v1.StatefulSet-ingester.yaml
loki/apps-v1.StatefulSet-querier.yaml
loki/apps-v1.StatefulSet-ruler.yaml
loki/index-gateway/apps-v1.StatefulSet-index-gateway.yaml

kustomize only understands name references if you use `serviceAccountName`
https://github.com/kubernetes-sigs/kustomize/blob/e5041bae6f3b536b764f96c1cf72d332a9c68c43/api/konfig/builtinpluginconsts/namereference.go#L349

loki: use serviceAccountName rather than serviceAccount

---

promtail/files/promtail.yaml

Support both kubernetes recommended labels and legacy labels.
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
Previously 'app' was used as the standard label for an application
name label. Many projects are now using the above recommended labels
so this commit supports both approaches.

promtail: update eventrouter label support

---

loki/files/config.yaml

loki: set max querier max look back as environment var with default

---

loki/alerting-rules.yaml

This alert is a little bit too noisy and could benefit from being
monitored over a longer period.
Closes #64

loki: reduce sensitivity of query latency alert

---

loki/alerting-rules.yaml

This alert fails under normal operation in many cases and causes
alert fatigue. This is being deleted until a more suitable alert
can be written.

loki: delete query latency alert

---

promtail/alerting-rules.yaml

Usually 0-length files are short-lived and are filtered by the `for: 15m`. However, in rare occasions they can live long enough to cause a false alarm. Filtering them out prevents this.

Don't alert on 0-length files that aren't being read.

---

promtail/files/promtail.yaml

Containerd logs are in `cri` format instead of `docker`, so we have to change the promtail ingestion format.
Ticket: BG-76807

add cri stage to promtail

---

loki-canary/kustomization.yaml
loki/kustomization.yaml
promtail/kustomization.yaml

- loki: bump docker images to v2.8.4
- loki-canary: bump docker images to v2.8.4
- promtail: bump docker images to v2.8.4
Closes #72

bump loki images v2.8.4
